# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
development:
   adapter: mysql2
   database: basic_spree_development
   username: root
   password: root
   host: localhost